name: Zip Files

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install -g uglify-js

    - name: Minify JavaScript
      run: uglifyjs ttfb-logger.js -o ttfb-logger.js

    - name: Create Plugin directory
      run: mkdir ttfb-by-isp ; cp ttfb-by-isp.php ttfb-by-isp; cp ttfb-logger.js ttfb-by-isp

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ttfb-by-isp-${{ github.ref_name }}
        path: ttfb-by-isp
